"""Inital

Revision ID: c08d3055f1d1
Revises: 
Create Date: 2020-01-20 22:14:53.360720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08d3055f1d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Employee_email'), 'Employee', ['email'], unique=True)
    op.create_table('LS Ester RM Stock Stage 1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fda_batch_no', sa.Integer(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('salicylic_acid', sa.Float(), nullable=True),
    sa.Column('dms', sa.Float(), nullable=True),
    sa.Column('caustic_soda_flakes', sa.Float(), nullable=True),
    sa.Column('hcl', sa.Float(), nullable=True),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('wet_cake', sa.Float(), nullable=True),
    sa.Column('dry_output', sa.Float(), nullable=True),
    sa.Column('p_yeild', sa.Float(), nullable=True),
    sa.Column('complete_date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('utilized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fda_batch_no')
    )
    op.create_table('LS Ester RM Stock Stage 2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fdb_batch_no', sa.String(length=128), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('fda', sa.Float(), nullable=True),
    sa.Column('fda_batch_no', sa.String(length=128), nullable=False),
    sa.Column('chlorosulphonic_acid', sa.Float(), nullable=True),
    sa.Column('thionyl_cholride', sa.Float(), nullable=True),
    sa.Column('liq_amonia', sa.Float(), nullable=True),
    sa.Column('sulphuric_acid', sa.Float(), nullable=True),
    sa.Column('wet_cake_after_csa_reaction', sa.Float(), nullable=True),
    sa.Column('wet_cake', sa.Float(), nullable=True),
    sa.Column('dry_output', sa.Float(), nullable=True),
    sa.Column('factor', sa.Float(), nullable=True),
    sa.Column('complete_date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('utilized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LS Ester RM Stock Stage 3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fdc_batch_no', sa.String(length=128), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('fdb', sa.Float(), nullable=True),
    sa.Column('fdb_batch_no', sa.String(length=128), nullable=False),
    sa.Column('ok_fresh', sa.Float(), nullable=True),
    sa.Column('ok_recovered', sa.Float(), nullable=True),
    sa.Column('ok_cf_ml', sa.Float(), nullable=True),
    sa.Column('sulphuric_acid', sa.Float(), nullable=True),
    sa.Column('part_A_wet_cake', sa.Float(), nullable=True),
    sa.Column('dmf_fresh', sa.Float(), nullable=True),
    sa.Column('dmf_recovered', sa.Float(), nullable=True),
    sa.Column('cmf_ml_dmf', sa.Float(), nullable=True),
    sa.Column('soda_ash', sa.Float(), nullable=True),
    sa.Column('charcoal', sa.Float(), nullable=True),
    sa.Column('final_wet_cake', sa.Float(), nullable=True),
    sa.Column('dry_output', sa.Float(), nullable=True),
    sa.Column('factor', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=128), nullable=True),
    sa.Column('complete_date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billsPDF',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('buyer_name', sa.String(length=300), nullable=False),
    sa.Column('bill_pdf', sa.LargeBinary(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('reminder_given', sa.Boolean(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billsPDF')
    op.drop_table('LS Ester RM Stock Stage 3')
    op.drop_table('LS Ester RM Stock Stage 2')
    op.drop_table('LS Ester RM Stock Stage 1')
    op.drop_index(op.f('ix_Employee_email'), table_name='Employee')
    op.drop_table('Employee')
    # ### end Alembic commands ###
